[package]
authors = ["Kenan Sulayman <kenan@sly.mn>"]
name = "tsu"
version = "0.1.0"

[dependencies]
rocket = "0.3.0"
rocket_codegen = "0.3.0"
rocket_contrib = "0.3.0"
serde = "1.0.10"
serde_derive = "1.0.10"
serde_json = "1.0.2"
